version: 2
jobs:
  bundle_dependencies:
    working_directory: ~/kokoro-admin-manager
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - kokoro-admin-manager-bundle-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: kokoro-admin-manager-bundle-{{ checksum "package.json" }}
          paths:
            - ~/kokoro-admin-manager/node_modules
      - run: yarn build:prod

  test:
    working_directory: ~/kokoro-admin-manager
    docker:
      - image: circleci/node:8.10.0
        environment:
          NODE_ENV: test
          MOCHA_FILE: /tmp/test-results/test-results.xml
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - kokoro-admin-manager-bundle-{{ checksum "package.json" }}
      - run: yarn stylelint && yarn run lint -- --format junit --output-file /tmp/test-results/test-results.xml && yarn test -- --reporter mocha-junit-reporter
      - run: mkdir -p /tmp/test-results
      - store_test_results:
          path: /tmp/test-results

  deploy_staging: 
    working_directory: ~/kokoro-admin-manager
    machine:
      enabled: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "22:05:dd:aa:84:77:85:5e:a1:f0:b0:a9:1d:08:0f:a9"
      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              git remote add deploy dokku@kokoro-app.tk:admin-manager
              git push deploy master
            fi

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - bundle_dependencies
      - test:
          requires:
            - bundle_dependencies
      - deploy_staging:
          requires:
            - test
